# Dockerfile
FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install  # includes devDependencies \
    && npm audit fix --force \
    && apk update && apk upgrade --no-cache

COPY . .

EXPOSE 5000

CMD ["node", "src/server.js"]
