version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: redis-cache-demo
    ports:
      - "3001:3000"  # host:container
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
      PORT: 3000
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - backend

volumes:
  redis-data:

networks:
  backend:
    driver: bridge
